name: "Alex P. Miller | Ph.D. Student at The Wharton School"
title: "Alex Miller's website"
markdown: kramdown
kramdown:
  input: GFM
description: "Alex Miller is a doctoral candidate in Information Systems at the Wharton School's department of Operations, Information, &amp; Decisions."
url: https://alex.miller.im
permalink: /posts/:title/
github_username: alexmill
