name: Alex Miller | Philadelphia, PA
markdown: redcarpet
pygments: true
description: "I'm Alex Miller, a Philadelphia-based programmer, mathematician, and student. Click to find out what I've been doing lately and connect with me online."
url: "http://alex.miller.im"
permalink: /posts/:title
