name: "Alex Miller | Ph.D. Student, Information Systems | The Wharton School"
title: "Alex Miller's website"
markdown: kramdown
kramdown:
  input: GFM
pygments: true
description: "I'm Alex Miller, a doctoral candidate at the Wharton School's department of Operations, Information, &amp; Decisions. Click to connect with me online."
url: http://alex.miller.im
permalink: /posts/:title
github_username: alexmill
