name: "Alex Miller | Developer & Analyst in Philadelphia, PA"
title: "Alex Miller's website"
markdown: kramdown
kramdown:
  input: GFM
pygments: true
description: "I'm Alex Miller, a Philadelphia-based developer, mathematician, and student. Click to find out what I've been doing lately and connect with me online."
url: http://alex.miller.im
permalink: /posts/:title
github_username: alexpmil
